[package]
name = "mail-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
google-gmail1 = "*"
serde = "^1.0"
serde_json = "^1.0"
clap = "2.33"

[[bin]]
name = "mail-manager"
path = "src/main.rs"